name: Docker Build & Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-nginx-demo .

      - name: Run Docker container
        run: docker run --rm -d -p 8080:80 my-nginx-demo

      - name: Wait and test
        run: |
          sleep 5
          curl http://localhost:8080
